# Generated by Django 5.0.1 on 2024-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionId', models.IntegerField(null=True)),
                ('actionKey', models.CharField(max_length=20, null=True)),
                ('anonymized', models.BooleanField(null=True)),
                ('data', models.CharField(max_length=200)),
                ('dataDuration', models.IntegerField(null=True)),
                ('dataId', models.IntegerField(null=True)),
                ('dataName', models.CharField(max_length=200)),
                ('dataNetId', models.IntegerField(null=True)),
                ('dataPrice', models.IntegerField(null=True)),
                ('dataSeviceId', models.IntegerField(null=True)),
                ('dataTsId', models.IntegerField(null=True)),
                ('date', models.IntegerField(null=True)),
                ('deviceId', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ipId', models.IntegerField(null=True)),
                ('manual', models.BooleanField(null=True)),
                ('profileId', models.IntegerField(null=True)),
                ('reaonId', models.IntegerField(null=True)),
                ('reasonKey', models.CharField(max_length=20, null=True)),
                ('recordId', models.IntegerField(null=True)),
                ('smartcardId', models.CharField(max_length=50)),
                ('subscriberCode', models.CharField(max_length=50)),
                ('timestamp', models.DateField(null=True)),
                ('whoisCountry', models.CharField(max_length=20, null=True)),
                ('whoisIsp', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
