# Generated by Django 5.0.1 on 2024-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='actionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='actionKey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='anonymized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='data',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataDuration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataNetId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataSeviceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='dataTsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='deviceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='ipId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='manual',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='profileId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='reaonId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='reasonKey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='recordId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='whoisCountry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='whoisIsp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
