# Generated by Django 5.0.1 on 2024-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0002_alter_telemetria_actionid_alter_telemetria_actionkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='dataName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='smartcardId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='subscriberCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
