# Generated by Django 5.0.1 on 2024-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0003_alter_telemetria_dataname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
