# Generated by Django 5.0.1 on 2024-02-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0005_actioni7_actionid7_8_actionid8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionI7',
        ),
        migrations.DeleteModel(
            name='ActionId7_8',
        ),
        migrations.DeleteModel(
            name='ActionId8',
        ),
    ]
